In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('TelecomX_Data.csv')
df

,ID Cliente,Churn,Gênero,Idoso,Parceiro,Dependentes,Tempo de Contrato (meses),Serviço de Telefone,Linhas Múltiplas,Serviço de Internet,...,Proteção de Dispositivo,Suporte Técnico,Canal de TV,Canal de Filmes,Tipo de Contrato,Fatura Online,Método de Pagamento,Cobrança Mensal,Cobrança Total,Valor Diário
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.9,1.838333
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7,2.836667
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6,1.966667

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID Cliente                 7267 non-null   object
 1   Churn                      7043 non-null   object
 2   Gênero                     7267 non-null   object
 3   Idoso                      7267 non-null   int64
 4   Parceiro                   7267 non-null   object
 5   Dependentes                7267 non-null   object
 6   Tempo de Contrato (meses)  7267 non-null   int64
 7   Serviço de Telefone        7267 non-null   object
 8   Linhas Múltiplas           7267 non-null   object
 9   Serviço de Internet        7267 non-null   object
 10  Segurança Online           7267 non-null   object
 11  Backup Online              7267 non-null   object
 12  Proteção de Dispositivo    7267 non-null   object
 13  Suporte Técnico            7267 non-null   object
 14  Canal de TV                7267 non-null   object
 15  Canal de Filmes            7267 non-null   object
 16  Tipo de Contrato           7267 non-null   object
 17  Fatura Online              7267 non-null   object
 18  Método de Pagamento        7267 non-null   object
 19  Cobrança Mensal            7267 non-null   float64
 20  Cobrança Total             7267 non-null   object
 21  Valor Diário               7267 non-null   float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [8]:
df.drop(columns=['ID Cliente'], inplace=True)

In [9]:
df.head()

,Churn,Gênero,Idoso,Parceiro,Dependentes,Tempo de Contrato (meses),Serviço de Telefone,Linhas Múltiplas,Serviço de Internet,Segurança Online,...,Proteção de Dispositivo,Suporte Técnico,Canal de TV,Canal de Filmes,Tipo de Contrato,Fatura Online,Método de Pagamento,Cobrança Mensal,Cobrança Total,Valor Diário
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4,2.796667