In [2]:
import pandas as pd

In [29]:
df = pd.read_csv('TelecomX_Data.csv')
df

,ID Cliente,Churn,Gênero,Idoso,Parceiro,Dependentes,Tempo de Contrato (meses),Serviço de Telefone,Linhas Múltiplas,Serviço de Internet,...,Proteção de Dispositivo,Suporte Técnico,Canal de TV,Canal de Filmes,Tipo de Contrato,Fatura Online,Método de Pagamento,Cobrança Mensal,Cobrança Total,Valor Diário
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.9,1.838333
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7,2.836667
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6,1.966667

In [30]:
df = df.drop(columns=['Tempo de Contrato (meses)','Cobrança Mensal','Cobrança Total','Valor Diário'], axis=1)

In [33]:
df

,ID Cliente,Churn,Gênero,Idoso,Parceiro,Dependentes,Serviço de Telefone,Linhas Múltiplas,Serviço de Internet,Segurança Online,Backup Online,Proteção de Dispositivo,Suporte Técnico,Canal de TV,Canal de Filmes,Tipo de Contrato,Fatura Online,Método de Pagamento
0,0002-ORFBO,No,Female,0,Yes,Yes,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check
1,0003-MKNFE,No,Male,0,No,No,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check
2,0004-TLHLJ,Yes,Male,0,No,No,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check
3,0011-IGKFF,Yes,Male,1,Yes,No,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check
4,0013-EXCHZ,Yes,Female,1,Yes,No,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check
7263,9992-RRAMN,Yes,Male,0,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check
7264,9992-UJOEL,No,Male,0,No,No,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
7265,9993-LHIEB,No,Male,0,Yes,Yes,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check
7266,9995-HOTOH,No,Male,0,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check

In [34]:
df = df.drop(columns=['ID Cliente'], axis=1)

In [35]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\desant\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\desant\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\desant\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\desant\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\desant\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [37]:
x=df.drop(columns=['Churn'], axis=1)
y=df['Churn']

In [38]:
x

,Gênero,Idoso,Parceiro,Dependentes,Serviço de Telefone,Linhas Múltiplas,Serviço de Internet,Segurança Online,Backup Online,Proteção de Dispositivo,Suporte Técnico,Canal de TV,Canal de Filmes,Tipo de Contrato,Fatura Online,Método de Pagamento
0,Female,0,Yes,Yes,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check
1,Male,0,No,No,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check
2,Male,0,No,No,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check
3,Male,1,Yes,No,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check
4,Female,1,Yes,No,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,Female,0,No,No,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check
7263,Male,0,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check
7264,Male,0,No,No,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
7265,Male,0,Yes,Yes,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check
7266,Male,0,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check

In [39]:
colunas = x.columns
colunas

Index(['Gênero', 'Idoso', 'Parceiro', 'Dependentes', 'Serviço de Telefone',
       'Linhas Múltiplas', 'Serviço de Internet', 'Segurança Online',
       'Backup Online', 'Proteção de Dispositivo', 'Suporte Técnico',
       'Canal de TV', 'Canal de Filmes', 'Tipo de Contrato', 'Fatura Online',
       'Método de Pagamento'],
      dtype='object')

In [42]:
one_hot = make_column_transformer((
    OneHotEncoder(drop='if_binary'), 
    ['Gênero','Idoso','Parceiro','Serviço de Telefone','Linhas Múltiplas','Método de Pagamento',
     'Tipo de Contrato']
),
remainder='passthrough', 
sparse_threshold=0)